### ISSUE TITLE
Incorrect Private Key Prefix

### ISSUE THREAD

**Issue by Tech1k** [Tech1k/electrum-sum#1]
@jakesum [https://github.com/Tech1k/electrum-sum/blob/master/electrum_sum/constants.py#L56](url)

**Comment by jakesum** [comment]
Looking into this and will report back

**Comment by Tech1k** [comment]
@DCGoD Jake told me that you could help out? Any help would be much appreciated!

**Comment by Tech1k** [comment]
I might have figured it out and I'm going to close this pull request due to inactivity.
